project:
  type: website

website:
  title: "my-website"
  navbar:
    left:
      - text: "About Me"
        href: aboutme.qmd
      - text: "Projects"
        href: projects.qmd
      - text: "CV"
        href: cv.qmd
      - text: "Contact"
        href: contact.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



