project:
  type: website
  output-dir: ../docs

website:
  title: "Cassie Lu Portfolio"
  navbar:
    left:
      - text: "About Me"
        href: aboutme.qmd
      - text: "Projects"
        href: projects.qmd
      - text: "CV"
        href: cv.qmd
      - text: "Contact"
        href: contact.qmd

format:
  html:
    theme:
      - journal
    css: styles.css
    toc: true



